name: Release Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: arm64
            binary_name: maze-adventure-macos-arm64

          - os: windows-latest
            goos: windows
            goarch: amd64
            binary_name: maze-adventure-windows-amd64.exe

          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_name: maze-adventure-linux-amd64

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build binary
        run: |
          mkdir -p dist
          go build -v -o dist/${{ matrix.binary_name }} ./cmd/main
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ matrix.binary_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
