name: Build for macOS ARM64

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos-arm64:
    name: Build for macOS (ARM64)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=arm64 go build -o dist/maze-adventure-macos-arm64 ./cmd/main

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: maze-adventure-macos-arm64
          path: dist/maze-adventure-macos-arm64
